CREATE TABLE profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    bio VARCHAR(500),
    profile_picture_path VARCHAR(500),
    preferred_language VARCHAR(10) DEFAULT 'fr',
    receive_sms_notifications BOOLEAN DEFAULT TRUE,
    receive_email_notifications BOOLEAN DEFAULT FALSE,
    receive_push_notifications BOOLEAN DEFAULT TRUE,
    skills VARCHAR(1000),
    date_of_birth VARCHAR(20),
    gender ENUM('MALE', 'FEMALE', 'OTHER'),
    marital_status VARCHAR(50),
    dependents_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    version BIGINT DEFAULT 0,
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;