spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microcredit_db_dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.microcredit: TRACE
    org.springframework.data.mongodb: DEBUG