package com.agribind.communication.mapper;

import com.agribind.communication.dto.AlertRequest;
import com.agribind.communication.dto.AlertResponse;
import com.agribind.communication.model.Alert;
import com.agribind.communication.model.AlertStatus;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Manual mapper for Alert entity and DTOs
 */
@Component
public class AlertMapper {

    /**
     * Convert Alert entity to AlertResponse
     */
    public AlertResponse toResponse(Alert alert) {
        if (alert == null) {
            return null;
        }

        AlertResponse response = new AlertResponse();
        response.setId(alert.getId());
        response.setAlertId(alert.getAlertId());
        response.setType(alert.getType());
        response.setPriority(alert.getPriority());
        response.setTitle(alert.getTitle());
        response.setRecipientCount(alert.getRecipientCount());
        response.setChannels(alert.getChannels());
        response.setDeliveryRate(alert.getDeliveryRate());
        response.setStatus(alert.getStatus());
        response.setCreatedAt(alert.getCreatedAt());

        return response;
    }

    /**
     * Convert Alert entity to AlertResponse using Builder pattern
     */
    public AlertResponse toResponseWithBuilder(Alert alert) {
        if (alert == null) {
            return null;
        }

        return AlertResponse.builder()
                .id(alert.getId())
                .alertId(alert.getAlertId())
                .type(alert.getType())
                .priority(alert.getPriority())
                .title(alert.getTitle())
                .recipientCount(alert.getRecipientCount())
                .channels(alert.getChannels())
                .deliveryRate(alert.getDeliveryRate())
                .status(alert.getStatus())
                .createdAt(alert.getCreatedAt())
                .build();
    }

    /**
     * Convert AlertRequest to Alert entity
     * Note: alertId, recipientCount, deliveryRate, and status are not in AlertRequest
     * These should be set separately in service layer
     */
    public Alert toEntity(AlertRequest request) {
        if (request == null) {
            return null;
        }

        Alert alert = new Alert();
        // id is auto-generated by database, so we don't set it
        // alertId should be generated separately (e.g., UUID or sequence)
        alert.setType(request.getType());
        alert.setPriority(request.getPriority());
        alert.setTitle(request.getTitle());
        alert.setContent(request.getContent());

        // Copy channels list
        if (request.getChannels() != null) {
            alert.setChannels(List.copyOf(request.getChannels()));
        } else {
            alert.setChannels(List.of());
        }

        // recipientCount, deliveryRate, and status will be set by @PrePersist or service logic
        // createdAt will be set by @PrePersist

        return alert;
    }

    /**
     * Convert AlertRequest to Alert entity with default values
     * Includes generating a default alertId and setting initial status
     */
    public Alert toEntityWithDefaults(AlertRequest request, String generatedAlertId, Integer estimatedRecipientCount) {
        if (request == null) {
            return null;
        }

        Alert alert = toEntity(request);

        // Set generated values
        alert.setAlertId(generatedAlertId);
        alert.setRecipientCount(estimatedRecipientCount != null ? estimatedRecipientCount : 0);
        alert.setStatus(AlertStatus.ACTIVE); // Initial status
        alert.setDeliveryRate(0.0); // Initial delivery rate

        return alert;
    }

    /**
     * Update existing Alert entity from DTO
     * Note: id, alertId, and createdAt are not updated as they shouldn't change
     */
    public void updateEntityFromDto(AlertRequest dto, Alert alert) {
        if (dto == null || alert == null) {
            return;
        }

        // Do NOT update: id, alertId, createdAt, sentAt

        // Update fields from DTO
        alert.setType(dto.getType());
        alert.setPriority(dto.getPriority());
        alert.setTitle(dto.getTitle());
        alert.setContent(dto.getContent());

        // Update channels if provided
        if (dto.getChannels() != null) {
            alert.setChannels(List.copyOf(dto.getChannels()));
        }

        // Note: recipientCount, deliveryRate, and status are not in AlertRequest
        // These should be updated separately based on business logic
    }

    /**
     * Convert list of Alert entities to list of AlertResponse
     */
    public List<AlertResponse> toResponseList(List<Alert> alerts) {
        if (alerts == null) {
            return List.of();
        }

        return alerts.stream()
                .map(this::toResponse)
                .toList();
    }

    /**
     * Convert Alert entity to a summary response (with only essential fields)
     */
    public AlertResponse toSummaryResponse(Alert alert) {
        if (alert == null) {
            return null;
        }

        return AlertResponse.builder()
                .id(alert.getId())
                .alertId(alert.getAlertId())
                .type(alert.getType())
                .priority(alert.getPriority())
                .title(alert.getTitle())
                .status(alert.getStatus())
                .createdAt(alert.getCreatedAt())
                .build();
    }

    /**
     * Create Alert entity from minimal parameters (useful for testing)
     */
    public Alert createMinimalAlert(String title, String content, String alertId) {
        Alert alert = new Alert();
        alert.setTitle(title);
        alert.setContent(content);
        alert.setAlertId(alertId);
        alert.setRecipientCount(0);
        alert.setDeliveryRate(0.0);
        alert.setStatus(AlertStatus.ACTIVE);
        alert.setChannels(List.of("SMS")); // Default channel
        return alert;
    }
}