package com.agribind.communication.mapper;

import com.agribind.communication.dto.ResourceRequestDto;
import com.agribind.communication.dto.ResourceRequestResponse;
import com.agribind.communication.model.ResourceRequest;
import com.agribind.communication.model.RequestStatus;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Manual mapper for ResourceRequest entity and DTOs
 */
@Component
public class ResourceRequestMapper {

    /**
     * Convert ResourceRequest entity to DTO
     */
    public ResourceRequestDto toDto(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        ResourceRequestDto dto = new ResourceRequestDto();
        dto.setResourceName(request.getResourceName());
        dto.setQuantity(request.getQuantity());
        dto.setUnit(request.getUnit());
        dto.setUrgency(request.getUrgency());
        dto.setRequestedBy(request.getRequestedBy());
        dto.setRequestedByZone(request.getRequestedByZone());

        return dto;
    }

    /**
     * Convert ResourceRequest entity to DTO using Builder pattern
     */
    public ResourceRequestDto toDtoWithBuilder(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        return ResourceRequestDto.builder()
                .resourceName(request.getResourceName())
                .quantity(request.getQuantity())
                .unit(request.getUnit())
                .urgency(request.getUrgency())
                .requestedBy(request.getRequestedBy())
                .requestedByZone(request.getRequestedByZone())
                .build();
    }

    /**
     * Convert ResourceRequestDto to entity
     */
    public ResourceRequest toEntity(ResourceRequestDto dto) {
        if (dto == null) {
            return null;
        }

        ResourceRequest request = new ResourceRequest();
        // id is auto-generated by database, so we don't set it
        // requestId should be generated separately
        request.setResourceName(dto.getResourceName());
        request.setQuantity(dto.getQuantity());
        request.setUnit(dto.getUnit());
        request.setUrgency(dto.getUrgency());
        request.setRequestedBy(dto.getRequestedBy());
        request.setRequestedByZone(dto.getRequestedByZone());

        // These will be set by @PrePersist or service logic:
        // - requestId (should be generated)
        // - status (@PrePersist sets to PENDING)
        // - suppliersMatched (@PrePersist sets to 0)
        // - requestDate (@PrePersist sets to now)
        // - fulfilledDate (when request is fulfilled)

        return request;
    }

    /**
     * Convert ResourceRequestDto to entity with generated request ID
     */
    public ResourceRequest toEntityWithRequestId(ResourceRequestDto dto, String requestId) {
        if (dto == null) {
            return null;
        }

        ResourceRequest request = toEntity(dto);
        request.setRequestId(requestId);

        return request;
    }

    /**
     * Convert ResourceRequest entity to Response DTO
     */
    public ResourceRequestResponse toResponse(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        ResourceRequestResponse response = new ResourceRequestResponse();
        response.setId(request.getId());
        response.setRequestId(request.getRequestId());
        response.setResourceName(request.getResourceName());
        response.setQuantity(request.getQuantity());
        response.setUrgency(request.getUrgency());
        response.setStatus(request.getStatus());
        response.setSuppliersMatched(request.getSuppliersMatched());
        response.setRequestDate(request.getRequestDate());

        return response;
    }

    /**
     * Convert ResourceRequest entity to Response DTO using Builder pattern
     */
    public ResourceRequestResponse toResponseWithBuilder(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        return ResourceRequestResponse.builder()
                .id(request.getId())
                .requestId(request.getRequestId())
                .resourceName(request.getResourceName())
                .quantity(request.getQuantity())
                .urgency(request.getUrgency())
                .status(request.getStatus())
                .suppliersMatched(request.getSuppliersMatched())
                .requestDate(request.getRequestDate())
                .build();
    }

    /**
     * Update existing ResourceRequest entity from DTO
     */
    public void updateEntityFromDto(ResourceRequestDto dto, ResourceRequest request) {
        if (dto == null || request == null) {
            return;
        }

        // Do NOT update: id, requestId, requestDate, fulfilledDate,
        // suppliersMatched (should be updated via business logic)

        // Update fields from DTO
        request.setResourceName(dto.getResourceName());
        request.setQuantity(dto.getQuantity());
        request.setUnit(dto.getUnit());
        request.setUrgency(dto.getUrgency());
        request.setRequestedBy(dto.getRequestedBy());
        request.setRequestedByZone(dto.getRequestedByZone());

        // Note: status should be updated via separate business methods
        // to maintain proper state transitions
    }

    /**
     * Convert list of ResourceRequest entities to list of Response DTOs
     */
    public List<ResourceRequestResponse> toResponseList(List<ResourceRequest> requests) {
        if (requests == null) {
            return List.of();
        }

        return requests.stream()
                .map(this::toResponse)
                .toList();
    }

    /**
     * Convert list of ResourceRequest entities to list of DTOs
     */
    public List<ResourceRequestDto> toDtoList(List<ResourceRequest> requests) {
        if (requests == null) {
            return List.of();
        }

        return requests.stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Create a summary response (with only essential fields)
     */
    public ResourceRequestResponse toSummaryResponse(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        return ResourceRequestResponse.builder()
                .id(request.getId())
                .requestId(request.getRequestId())
                .resourceName(request.getResourceName())
                .quantity(request.getQuantity())
                .urgency(request.getUrgency())
                .status(request.getStatus())
                .build();
    }

    /**
     * Create a detailed response with additional calculated fields
     */
    public ResourceRequestResponse toDetailedResponse(ResourceRequest request) {
        if (request == null) {
            return null;
        }

        ResourceRequestResponse response = toResponse(request);
        // Additional fields could be added here if needed
        return response;
    }

    /**
     * Update request status with proper state transitions
     */
    public void updateRequestStatus(ResourceRequest request, RequestStatus newStatus) {
        if (request == null) {
            return;
        }

        // Validate state transition (basic validation)
        if (!isValidStatusTransition(request.getStatus(), newStatus)) {
            throw new IllegalStateException(
                String.format("Invalid status transition from %s to %s",
                    request.getStatus(), newStatus));
        }

        request.setStatus(newStatus);

        // Set fulfilled date if status is FULFILLED
        if (newStatus == RequestStatus.FULFILLED) {
            request.setFulfilledDate(LocalDateTime.now());
        }
    }

    /**
     * Validate status transitions
     */
    private boolean isValidStatusTransition(RequestStatus current, RequestStatus next) {
        // Basic validation - can be expanded based on business rules
        if (current == null || next == null) {
            return false;
        }

        // Can't go backwards in most cases (except maybe from IN_PROGRESS back to PENDING)
        switch (next) {
            case PENDING:
                // Can only go to PENDING from IN_PROGRESS (e.g., if matching fails)
                return current == RequestStatus.IN_PROGRESS;
            case IN_PROGRESS:
                return current == RequestStatus.PENDING || current == RequestStatus.SUPPLIER_MATCHED;
            case SUPPLIER_MATCHED:
                return current == RequestStatus.IN_PROGRESS;
            case FULFILLED:
                return current == RequestStatus.SUPPLIER_MATCHED;
            case CANCELLED:
                // Can cancel from any state except FULFILLED
                return current != RequestStatus.FULFILLED;
            default:
                return false;
        }
    }

    /**
     * Update suppliers matched count
     */
    public void updateSuppliersMatched(ResourceRequest request, Integer suppliersMatched) {
        if (request == null) {
            return;
        }

        request.setSuppliersMatched(suppliersMatched != null ? suppliersMatched : 0);

        // Auto-update status based on suppliers matched
        if (suppliersMatched != null && suppliersMatched > 0) {
            request.setStatus(RequestStatus.SUPPLIER_MATCHED);
        } else if (request.getStatus() == RequestStatus.SUPPLIER_MATCHED &&
                  (suppliersMatched == null || suppliersMatched == 0)) {
            request.setStatus(RequestStatus.IN_PROGRESS);
        }
    }

    /**
     * Create ResourceRequest from minimal parameters (for testing)
     */
    public ResourceRequest createMinimalRequest(String resourceName, Integer quantity,
                                               String requestedBy, String requestId) {
        ResourceRequest request = new ResourceRequest();
        request.setRequestId(requestId);
        request.setResourceName(resourceName);
        request.setQuantity(quantity);
        request.setRequestedBy(requestedBy);
        request.setUrgency(com.agribind.communication.model.UrgencyLevel.MEDIUM); // Default
        request.setUnit("units"); // Default
        request.setRequestedByZone("General"); // Default

        return request;
    }
}