package com.agribind.communication.mapper;

import com.agribind.communication.dto.MessageTemplateDto;
import com.agribind.communication.model.MessageTemplate;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Manual mapper for MessageTemplate entity and DTOs
 */
@Component
public class TemplateMapper {

    /**
     * Convert MessageTemplate entity to DTO
     */
    public MessageTemplateDto toDto(MessageTemplate template) {
        if (template == null) {
            return null;
        }

        MessageTemplateDto dto = new MessageTemplateDto();
        dto.setId(template.getId());
        dto.setName(template.getName());
        dto.setContent(template.getContent());
        dto.setVariables(template.getVariables());

        return dto;
    }

    /**
     * Convert MessageTemplate entity to DTO using Builder pattern
     */
    public MessageTemplateDto toDtoWithBuilder(MessageTemplate template) {
        if (template == null) {
            return null;
        }

        return MessageTemplateDto.builder()
                .id(template.getId())
                .name(template.getName())
                .content(template.getContent())
                .variables(template.getVariables())
                .build();
    }

    /**
     * Convert MessageTemplateDto to entity
     */
    public MessageTemplate toEntity(MessageTemplateDto dto) {
        if (dto == null) {
            return null;
        }

        MessageTemplate template = new MessageTemplate();
        // id is auto-generated by database, so we don't set it from DTO
        template.setName(dto.getName());
        template.setContent(dto.getContent());

        // Copy variables list
        if (dto.getVariables() != null) {
            template.setVariables(List.copyOf(dto.getVariables()));
        } else {
            template.setVariables(List.of());
        }

        // createdAt will be set by @PrePersist

        return template;
    }

    /**
     * Update existing MessageTemplate entity from DTO
     */
    public void updateEntityFromDto(MessageTemplateDto dto, MessageTemplate template) {
        if (dto == null || template == null) {
            return;
        }

        // Do NOT update: id, createdAt

        // Update fields from DTO
        template.setName(dto.getName());
        template.setContent(dto.getContent());

        // Update variables if provided
        if (dto.getVariables() != null) {
            template.setVariables(List.copyOf(dto.getVariables()));
        }
    }

    /**
     * Convert list of MessageTemplate entities to list of DTOs
     */
    public List<MessageTemplateDto> toDtoList(List<MessageTemplate> templates) {
        if (templates == null) {
            return List.of();
        }

        return templates.stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Create a summary DTO (with only essential fields)
     */
    public MessageTemplateDto toSummaryDto(MessageTemplate template) {
        if (template == null) {
            return null;
        }

        MessageTemplateDto dto = new MessageTemplateDto();
        dto.setId(template.getId());
        dto.setName(template.getName());
        // Don't include content and variables in summary
        return dto;
    }

    /**
     * Create a summary DTO using Builder pattern
     */
    public MessageTemplateDto toSummaryDtoWithBuilder(MessageTemplate template) {
        if (template == null) {
            return null;
        }

        return MessageTemplateDto.builder()
                .id(template.getId())
                .name(template.getName())
                .build();
    }

    /**
     * Create a preview DTO (with truncated content for listings)
     */
    public MessageTemplateDto toPreviewDto(MessageTemplate template, int maxContentLength) {
        if (template == null) {
            return null;
        }

        MessageTemplateDto dto = toDto(template);

        // Truncate content for preview
        if (dto.getContent() != null && dto.getContent().length() > maxContentLength) {
            dto.setContent(dto.getContent().substring(0, maxContentLength) + "...");
        }

        return dto;
    }

    /**
     * Create MessageTemplate from minimal parameters
     */
    public MessageTemplate createMinimalTemplate(String name, String content) {
        MessageTemplate template = new MessageTemplate();
        template.setName(name);
        template.setContent(content);
        template.setVariables(extractVariablesFromContent(content));

        return template;
    }

    /**
     * Extract variable names from template content
     * Assumes variables are in format {{variableName}}
     */
    public List<String> extractVariablesFromContent(String content) {
        if (content == null || content.isEmpty()) {
            return List.of();
        }

        List<String> variables = new java.util.ArrayList<>();
        int startIndex = content.indexOf("{{");

        while (startIndex != -1) {
            int endIndex = content.indexOf("}}", startIndex);
            if (endIndex != -1) {
                String variable = content.substring(startIndex + 2, endIndex).trim();
                if (!variable.isEmpty() && !variables.contains(variable)) {
                    variables.add(variable);
                }
                startIndex = content.indexOf("{{", endIndex);
            } else {
                break;
            }
        }

        return List.copyOf(variables);
    }

    /**
     * Apply variables to template content
     * Replaces {{variableName}} with actual values
     */
    public String applyVariables(String templateContent, java.util.Map<String, String> variables) {
        if (templateContent == null) {
            return null;
        }

        if (variables == null || variables.isEmpty()) {
            return templateContent;
        }

        String result = templateContent;
        for (java.util.Map.Entry<String, String> entry : variables.entrySet()) {
            String placeholder = "{{" + entry.getKey() + "}}";
            result = result.replace(placeholder, entry.getValue() != null ? entry.getValue() : "");
        }

        return result;
    }

    /**
     * Apply variables to MessageTemplate and return processed content
     */
    public String applyVariables(MessageTemplate template, java.util.Map<String, String> variables) {
        if (template == null || template.getContent() == null) {
            return null;
        }

        return applyVariables(template.getContent(), variables);
    }

    /**
     * Validate template content
     * Checks for unmatched variable placeholders
     */
    public boolean validateTemplate(MessageTemplate template) {
        if (template == null || template.getContent() == null) {
            return false;
        }

        List<String> extractedVars = extractVariablesFromContent(template.getContent());
        List<String> declaredVars = template.getVariables();

        // If no variables declared and none found in content, it's valid
        if ((declaredVars == null || declaredVars.isEmpty()) && extractedVars.isEmpty()) {
            return true;
        }

        // Check if all variables in content are declared
        for (String var : extractedVars) {
            if (declaredVars == null || !declaredVars.contains(var)) {
                return false; // Undeclared variable in content
            }
        }

        // Check if all declared variables are used in content
        if (declaredVars != null) {
            for (String var : declaredVars) {
                String placeholder = "{{" + var + "}}";
                if (!template.getContent().contains(placeholder)) {
                    return false; // Declared variable not used in content
                }
            }
        }

        return true;
    }

    /**
     * Validate template DTO before conversion
     */
    public boolean validateDto(MessageTemplateDto dto) {
        if (dto == null || dto.getContent() == null) {
            return false;
        }

        List<String> extractedVars = extractVariablesFromContent(dto.getContent());
        List<String> declaredVars = dto.getVariables();

        // If no variables declared and none found in content, it's valid
        if ((declaredVars == null || declaredVars.isEmpty()) && extractedVars.isEmpty()) {
            return true;
        }

        // Check if all variables in content are declared
        for (String var : extractedVars) {
            if (declaredVars == null || !declaredVars.contains(var)) {
                return false; // Undeclared variable in content
            }
        }

        // Check if all declared variables are used in content
        if (declaredVars != null) {
            for (String var : declaredVars) {
                String placeholder = "{{" + var + "}}";
                if (!dto.getContent().contains(placeholder)) {
                    return false; // Declared variable not used in content
                }
            }
        }

        return true;
    }

    /**
     * Create a copy of template with new name
     */
    public MessageTemplate copyTemplate(MessageTemplate original, String newName) {
        if (original == null) {
            return null;
        }

        MessageTemplate copy = new MessageTemplate();
        copy.setName(newName != null ? newName : original.getName() + " (Copy)");
        copy.setContent(original.getContent());
        copy.setVariables(new java.util.ArrayList<>(original.getVariables()));

        return copy;
    }

    /**
     * Create a DTO copy of template with new name
     */
    public MessageTemplateDto copyTemplateDto(MessageTemplateDto original, String newName) {
        if (original == null) {
            return null;
        }

        return MessageTemplateDto.builder()
                .name(newName != null ? newName : original.getName() + " (Copy)")
                .content(original.getContent())
                .variables(original.getVariables() != null ?
                    new java.util.ArrayList<>(original.getVariables()) : null)
                .build();
    }

    /**
     * Merge template updates (for partial updates)
     */
    public void mergeTemplate(MessageTemplateDto updates, MessageTemplate existing) {
        if (updates == null || existing == null) {
            return;
        }

        // Only update fields that are provided (not null)
        if (updates.getName() != null) {
            existing.setName(updates.getName());
        }

        if (updates.getContent() != null) {
            existing.setContent(updates.getContent());
            // Re-extract variables if content changed and no variables provided
            if (updates.getVariables() == null) {
                existing.setVariables(extractVariablesFromContent(updates.getContent()));
            }
        }

        if (updates.getVariables() != null) {
            existing.setVariables(List.copyOf(updates.getVariables()));
        }
    }

    /**
     * Auto-populate variables from content if not provided in DTO
     */
    public MessageTemplateDto autoPopulateVariables(MessageTemplateDto dto) {
        if (dto == null || dto.getContent() == null) {
            return dto;
        }

        // Only auto-populate if variables are null or empty
        if (dto.getVariables() == null || dto.getVariables().isEmpty()) {
            List<String> extractedVars = extractVariablesFromContent(dto.getContent());
            if (!extractedVars.isEmpty()) {
                dto.setVariables(extractedVars);
            }
        }

        return dto;
    }

    /**
     * Get template statistics
     */
    public TemplateStatistics getStatistics(MessageTemplate template) {
        if (template == null) {
            return null;
        }

        TemplateStatistics stats = new TemplateStatistics();
        stats.setVariableCount(template.getVariables() != null ? template.getVariables().size() : 0);
        stats.setContentLength(template.getContent() != null ? template.getContent().length() : 0);
        stats.setWordCount(countWords(template.getContent()));

        return stats;
    }

    /**
     * Helper method to count words in content
     */
    private int countWords(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }

        String[] words = content.trim().split("\\s+");
        return words.length;
    }

    /**
     * Statistics class for template analysis
     */
    public static class TemplateStatistics {
        private int variableCount;
        private int contentLength;
        private int wordCount;

        public int getVariableCount() { return variableCount; }
        public void setVariableCount(int variableCount) { this.variableCount = variableCount; }

        public int getContentLength() { return contentLength; }
        public void setContentLength(int contentLength) { this.contentLength = contentLength; }

        public int getWordCount() { return wordCount; }
        public void setWordCount(int wordCount) { this.wordCount = wordCount; }

        @Override
        public String toString() {
            return String.format("TemplateStatistics{variables=%d, length=%d, words=%d}",
                variableCount, contentLength, wordCount);
        }
    }
}